### ISSUE TITLE
LIFX not being discovered

### ISSUE THREAD

**Issue by s3719046** [Djelibeybi/ha-lifx-beta#11]
Heyo

I recently decided to updated HA (container) to the latest, and noticed that LIFX was not being discovered in the Integration (after finding it was undiscoverable).

I went through a bunch of troubleshooting and eventually ended up putting manual config in the configuration.yaml

lifx:
  light:
    - server: IP_ADDRESS
      port: 56700
      broadcast: IP_ADDRESS 

Then it started working (I can control and it discovered). Is there a current issue with the integration where it can't discover my lights?

**Comment by Djelibeybi** [comment]
Are you running this Beta or the built-in integration? If you're using this Beta integration, try enabling "Duplicate Discovery" in the Configure options on the Integrations page. If you're using the built-in integration, there is a fix waiting to be merged.

**Comment by s3719046** [comment]
I have the beta using HACS, I assume that you should already have the LIFX integration installed but not working (unavailable) to be able to see the configure options. So I manually added the light back in and it got discovered then checked the duplicate discovery option. Then I removed the manual setup in configuration.yaml and the light was still unavailable. 

If the beta was suppose to fix the discoverability. Then for me it doesn't work :( Unless I botched something up xd

So for now I'll just use the manual setup.

**Comment by Djelibeybi** [comment]
Are the `IP_ADDRESS` you're using for `server` and `broadcast` the same? They shouldn't be. :) Can you check Settings -> System -> Network and make sure Home Assistant's networking setup is correct?

**Comment by s3719046** [comment]
I have my HA on 192.168.1.120 (server) and my LIFX on 192.168.1.102 (Broadcast) for the configuration.yaml

**Comment by Djelibeybi** [comment]
Righto. It would be great if you could double-check that Home Assistant's networking config is corrent (via Settings -> System -> Network) and then enable debug logging and remove the hard-coded configuration so there's hopefully some clue as to why the discovery isn't working correctly.

**Comment by s3719046** [comment]
This is the Network config in HA
Auto Configure
Detected: eth0 (192.168.1.120/24)veth1ff5018 (192.168.1.120/24)

Here is the log when trying to add the LIFX integration using tail -f
> 2022-05-31 11:19:27 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection] [2834808520] Received {'type': 'manifest/get', 'integration': 'lifx', 'id': 53}
2022-05-31 11:19:27 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection] [2834808520] Sending {"id":53,"type":"result","success":true,"result":{"domain":"lifx","name":"LIFX","config_flow":true,"version":"2022.05.02","documentation":"https://www.home-assistant.io/integrations/lifx","requirements":["aiolifx==0.7.1","aiolifx_effects==0.2.2"],"dependencies":["network"],"homekit":{"models":["LIFX A19","LIFX Beam","LIFX BR30","LIFX Candle","LIFX Clean","LIFX Color","LIFX DLCOL","LIFX Dlight","LIFX DLWW","LIFX Downlight","LIFX Filament","LIFX GU10","LIFX Lightstrip","LIFX Mini","LIFX Nightvision","LIFX Pls","LIFX Plus","LIFX Tile","LIFX White","LIFX Z"]},"codeowners":["@Djelibeybi"],"iot_class":"local_polling","loggers":["aiolifx","aiolifx_effects","bitstring"],"is_built_in":false}}
2022-05-31 11:19:29 DEBUG (MainThread) [homeassistant.components.http.auth] Authenticated 192.168.1.253 for /api/config/config_entries/flow/3fe3e517ae6b3beba279040d92155632 using bearer token
2022-05-31 11:19:29 DEBUG (MainThread) [homeassistant.components.http.view] Serving /api/config/config_entries/flow/3fe3e517ae6b3beba279040d92155632 to 192.168.1.253 (auth: True)

**Comment by Djelibeybi** [comment]
Can you please add `custom_components.lifx: debug` to the `logger` config so I can see the beta integration debug logs too?

**Comment by s3719046** [comment]
This is my configuration yaml

```
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

logger:
  logs:
    custom_components.lifx: debug

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
```

So I deleted the LIFX integration in HA (not the beta in HACS) and this is the log results when I click submit when attempting to add the LIFX integration
```
2022-05-31 21:57:19 DEBUG (MainThread) [homeassistant.components.http.auth] Authenticated 192.168.1.253 for /api/config/config_entries/flow using bearer token
2022-05-31 21:57:19 DEBUG (MainThread) [homeassistant.components.http.view] Serving /api/config/config_entries/flow to 192.168.1.253 (auth: True)
2022-05-31 21:57:19 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection] [2856854696] Received {'type': 'manifest/get', 'integration': 'lifx', 'id': 80}
2022-05-31 21:57:19 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection] [2856854696] Sending {"id":80,"type":"result","success":true,"result":{"domain":"lifx","name":"LIFX","config_flow":true,"version":"2022.05.02","documentation":"https://www.home-assistant.io/integrations/lifx","requirements":["aiolifx==0.7.1","aiolifx_effects==0.2.2"],"dependencies":["network"],"homekit":{"models":["LIFX A19","LIFX Beam","LIFX BR30","LIFX Candle","LIFX Clean","LIFX Color","LIFX DLCOL","LIFX Dlight","LIFX DLWW","LIFX Downlight","LIFX Filament","LIFX GU10","LIFX Lightstrip","LIFX Mini","LIFX Nightvision","LIFX Pls","LIFX Plus","LIFX Tile","LIFX White","LIFX Z"]},"codeowners":["@Djelibeybi"],"iot_class":"local_polling","loggers":["aiolifx","aiolifx_effects","bitstring"],"is_built_in":false}}
2022-05-31 21:57:20 DEBUG (MainThread) [homeassistant.components.http.auth] Authenticated 192.168.1.253 for /api/config/config_entries/flow/7f62bdbf7cefd3459ff54f4b682ff397 using bearer token
2022-05-31 21:57:20 DEBUG (MainThread) [homeassistant.components.http.view] Serving /api/config/config_entries/flow/7f62bdbf7cefd3459ff54f4b682ff397 to 192.168.1.253 (auth: True)
```

I'm not seeing any new debug information

**Comment by s3719046** [comment]
Just a quick side note, I added manual discovery so that I can add the LIFX integration, found out that I needed to delete the beta version for LIFX to be integrated (automatically integrated). Which removed this error
```
2022-05-31 22:07:04 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration lifx which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-05-31 22:07:11 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 205, in async_init
    flow, result = await task
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 232, in _async_init
    result = await self._async_handle_step(flow, flow.init_step, data, init_done)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 330, in _async_handle_step
    raise UnknownStep(
homeassistant.data_entry_flow.UnknownStep: Handler LifxConfigFlowHandler doesn't support step import
```

Now that the integration is re-added, I reinstalled the LIFX beta and removed the manual discovery (server, broadcast), now light is unavailable.
I tried to add the full log to pastebin but it doesn't work. Is there a specific string I should grep for?

**Comment by Djelibeybi** [comment]
If you have debug logging enabled, it would be good to see all the log entries for `custom_components.lifx`

**Comment by cmccallu** [comment]
With the recent HA version series 2022.6.X I also lost my LIFX integration. I have tried using HACS and this repo without success 

I'm only seeing the following in the ha log 
2022-06-12 13:01:06 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration lifx which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

with the following set in my configuration
logger:
  default: info
  logs:
    custom_components.lifx: debug
    
 I'm running a dedicated rpi3 with Home Assistant OS 8.1.

The rpi3 is running on an IOT VLAN with the LIFX devices connected via an IOT SSID to the same IOT VLAN.

Happy to help debug if I can?

**Comment by Djelibeybi** [comment]
The lack of any debug logs indicates that there is no LIFX configuration, so please indicate how your LIFX integration is configured: do you have a `lifx:` configuration entry in your `configuration.yaml` file (or via `!include`) or did you add it via the Integrations page under settings? 

If you removed the LIFX configuration before installing this beta component, it should have automatically prompted you to configure it. If you didn't remove the LIFX configuration, the beta component should automatically use the existing configuration. 

If you have no configuration, both the core plugin and the custom component should automatically discover bulbs and prompt for configuration. Check your ignored integrations to see if it's hiding there perhaps.

**Comment by cmccallu** [comment]
Appreciate you getting back to me! I had it configured via Integrations page under settings and nothing in my configuration.yaml.

Initially I tried with this configuration and installed the beta component without any luck! I also tried removing the configuration under the  Integrations page and removing and re-installing the beta component and still nothing is found.

Thanks heaps Chris

**Comment by Djelibeybi** [comment]
If Home Assistant is not prompting you to enable the LIFX integration (built-in or beta via HACS) then it's auto detection mechanism isn't working properly. Please check your Home Assistant [network configuration](https://www.home-assistant.io/integrations/network) to ensure that it's configured correctly.

**Comment by cmccallu** [comment]
It was working 100% on 2022.5.X and earlier and the problem only surfaced on 2022.6.X. Nothing had changed in either my network setup or HA configuration and I have had LIFX integration working for a number of years!

Totally agree it does sound like auto detection is no longer working!

**Comment by Djelibeybi** [comment]
Do you have LIFX listed as active on your Integrations page? If not, can you add it manually to see what happens?

**Comment by Djelibeybi** [comment]
I'm going to close this now as the core integration is going with a completely different method for managing LIFX devices from `2022.8` onwoards.

**Comment by cmccallu** [comment]
Ok no worries at all! FYI I got it working again after rebuilding my hassio rpi3 and restoring a backup and setting up HACS + LIFX beta.
