### ISSUE TITLE
Object has no attribute error seen in logs

### ISSUE THREAD

**Issue by mark007** [Djelibeybi/ha-lifx-beta#4]
In the latest beta I saw this error in the logs.

I had noticed some bulbs never go unavailable even though they had been switched off all night so was checking the logs for clues.

I'm using these settings

Discovery Interval: 200
Message Reply Timeout: 2
Retry Count: 3
Grace Period: 180

Seems like an exception was thrown while handling of another. Some key that didn't exist.

```
Log Details (ERROR)
This error originated from a custom integration.
Logger: homeassistant
Source: custom_components/lifx/light.py:476
Integration: LIFX (documentation, issues)
First occurred: 02:45:18 (9 occurrences)
Last logged: 03:03:18

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/asyncio/locks.py", line 226, in wait
    await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
    fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/lifx/aiolifx/aiolifx.py", line 318, in try_sending
    myresult = await aio.wait_for(event.wait(), timeout_secs)
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 494, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/lifx/aiolifx/aiolifx.py", line 328, in try_sending
    self.unregister()
  File "/config/custom_components/lifx/aiolifx/aiolifx.py", line 223, in unregister
    self.parent.unregister(self)
  File "/config/custom_components/lifx/aiolifx/aiolifx.py", line 1424, in unregister
    self.parent.unregister(alight)
  File "/config/custom_components/lifx/light.py", line 476, in unregister
    entity.elapsed,
AttributeError: 'LIFXColor' object has no attribute 'elapsed'

```

**Comment by Djelibeybi** [comment]
Yep, 2.2.1 released a few hours ago should fix this.

**Comment by mark007** [comment]
Thank you!!
