### ISSUE TITLE
Latest beta introduce new python errors

### ISSUE THREAD

**Issue by mark007** [Djelibeybi/ha-lifx-beta#40]
With the latest beta as of today, the following errors are showing a lot in the logs.

This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/lifx/light.py:345
Integration: LIFX (documentation)
First occurred: 17 January 2023 at 21:49:02 (669 occurrences)
Last logged: 01:09:16

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 168, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 316, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 121, in async_update_listeners
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 381, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 556, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 599, in _async_write_ha_state
    attr.update(self.state_attributes or {})
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 986, in state_attributes
    color_mode = self._light_internal_color_mode
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 812, in _light_internal_color_mode
    if (color_mode := self.color_mode) is None:
  File "/config/custom_components/lifx/light.py", line 345, in color_mode
    has_sat = self.bulb.color[HSBK_SATURATION]
TypeError: 'NoneType' object is not subscriptable

And

Log Details (ERROR)
Logger: homeassistant.components.light
Source: helpers/entity_platform.py:536
Integration: Light ([documentation](https://www.home-assistant.io/integrations/light), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+light%22))
First occurred: 17 January 2023 at 21:48:33 (14 occurrences)
Last logged: 17 January 2023 at 21:48:33

Platform lifx does not generate unique IDs. ID 00:00:00:00:00:00 already exists - ignoring light.lifx_00_00_00_00_00_00

And also this one

Log Details (ERROR)
Logger: homeassistant.components.sensor
Source: custom_components/lifx/coordinator.py:150
Integration: Sensor ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
First occurred: 17 January 2023 at 21:48:33 (15 occurrences)
Last logged: 17 January 2023 at 21:48:33

Error while setting up lifx platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 289, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/lifx/sensor.py", line 47, in async_setup_entry
    async_add_entities([LIFXRssiSensor(coordinator, RSSI_SENSOR)])
  File "/config/custom_components/lifx/sensor.py", line 104, in __init__
    self._attr_native_unit_of_measurement = coordinator.rssi_uom
  File "/config/custom_components/lifx/coordinator.py", line 150, in rssi_uom
    if AwesomeVersion(self.device.host_firmware_version) <= RSSI_DBM_FW:
  File "/usr/local/lib/python3.10/site-packages/awesomeversion/awesomeversion.py", line 202, in __le__
    return self.__eq__(compareto) or self.__lt__(compareto)
  File "/usr/local/lib/python3.10/site-packages/awesomeversion/awesomeversion.py", line 176, in __lt__
    raise AwesomeVersionCompareException(
awesomeversion.exceptions.AwesomeVersionCompareException: Can't compare <unknown None> and <SimpleVer 2.77>

**Comment by Djelibeybi** [comment]
Thanks @mark007. I know what the problem is, I think. Will try and get an updated version out ASAP.

**Comment by mark007** [comment]
Thanks a lot. If you would prefer separate issues written for each log I can do that. As I pasted a lot in the one ticket here :)

**Comment by Djelibeybi** [comment]
Nah, it's fine. It's all caused by the same thing.
